site_name: SuperQ
site_author: Alvin Chen <bollinmore@gmail.com>
nav:
  - Home: index.md
  - About: about.md
  - BIOS Tool: 
    - Category: BIOS/bios_tool.md
    - smbios: BIOS/smbios.md
    - i2c: BIOS/i2c.md
    - gpio: BIOS/gpio.md
    - Variable: BIOS/variable.md
  - Leet Code:
    - 1. Two Sum: leetcode/math/two_sum.md
    - 2. Add Two Numbers: leetcode/math/add_two_numbers.md
    - 6. Zigzag Conversion: leetcode/string/zigzag_conversion.md
    - 7. Reverse Integer: leetcode/math/reverse_integer.md
    - 15. 3Sum: leetcode/two_pointers/3Sum.md
    - 16. 3Sum Closest: leetcode/two_pointers/3Sum_closest.md
    - 17. Letter Combinations of a Phone Number: leetcode/string/letter_combinations_of_a_phone_number.md
    - 45. Jump Game II: leetcode/dp/jump_game2.md
    - 49. Group Anagrams: leetcode/hash_table/group_anagrams.md
    - 55. Jump Game: leetcode/dp/jump_game.md
    - 56. Merge Intervals: leetcode/sorting/merge_intervals.md
    - 62. Unique Paths: leetcode/dp/unique_paths.md
    - 64. Minimum Path Sum: leetcode/dp/minimum_path_sum.md
    - 96. Unique Binary Search Trees: leetcode/dp/unique_binary_search_trees.md
    - 142. Linked List Cycle II: leetcode/dp/linked_list_cycle2.md
    - 134. Gas Station: leetcode/array/gas_station.md
    - 136. Single Number: leetcode/array/single-number.md
    - 141. Linked List Cycle: leetcode/two_pointers/linked-list-cycle.md
    - 144. Binary Tree Preorder Traversal: leetcode/binary_tree/binary-tree-preorder-traversal.md
    - 179. Largest Number: leetcode/sorting/largest_number.md
    - 217. Contains Duplicate: leetcode/sorting/contains_duplicate.md
    - 219. Contains Duplicate II: leetcode/hash_table/contains_duplicate2.md
    - 292. Nim Game: leetcode/math/nim_game.md
    - 374. Guess Number Higher or Lower: leetcode/binary_search/guess_number_higher_or_lower.md
    - 414. Third Maximum Number: leetcode/math/third_maximum_number.md
    - 424. Longest Repeating Character Replacement: leetcode/sliding_window/longest_repeating_character_replacement.md
    - 724. Find Pivot Index: leetcode/array/find_pivot_index.md
    - 1013. Partition Array Into Three Parts With Equal Sum: leetcode/array/partition_array_into_three_parts_with_equal_sum.md
  - Code Snippet:
    - Generate random negative integer: snippet/random_negative_int.md
  - Note:
    - CefPython, Upgrade CEF version: python/cefpython_upgrade_cef.md
    - PyInstaller: python/pyinstaller.md
    - Execute SQLite command without openning interactive shell: sqlite/run_cmd_wo_into_shell.md
    - Docker: 
      - Basic: docker/cookbook.md
      - Account: docker/account.md
      - Network: docker/network.md
      - RClone: docker/rclone.md
    - Lomorage: lomorage/basic.md
    - Git: git/cookbook.md
  - SBOM:
    - SPDX: sbom/spdx.md
    - FOSSology Intro: sbom/FOSSology_intro.md
    - ORT-FOSSology: sbom/ort-fossology.md
  - Raspberry Pi:
    - Nextcloud: raspberry_pi/nextcloud.md
    - PiKVM: raspberry_pi/pikvm.md
  - Python:
    - Troubleshooting: python/troubleshooting.md
    - Poetry: python/poetry.md
    - pip: python/pip.md
    - OCR: python/ocr.md

theme:
    name: material
    font: 
      text: Salsa
    logo: images/favicon.png
    favicon: images/favicon.png
    custom_dir: custom_theme/
    features:
      - content.code.copy

extra_css:
  - extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
    provider: google
    property: G-YKKXV0QL0S
